# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Alessia Visconti
tagline:          ''
description:      'Computational Biologist, PhD'
url:              http://alesssia.github.io/
baseurl:          /
lastmod:		  '20180506'

author:
  name:           'Alessia Visconti'
  url:            http://alesssia.github.io/
  email: 		  alessia.visconti@gmail.com 
  twitter_username: _alesssia
  github_username:  alesssia
  
paginate:         5
