# Dependencies
markdown:    kramdown
highlighter: rouge

# Permalinks
permalink:   pretty

# Setup
title:       Dr Alessia Visconti
tagline:     ''
description: 'PhD'
url:         http://alesssia.github.io/
baseurl:     /
lastmod:    '2023-04-06'

author:
  name:      'Alessia Visconti'
  url:       http://alesssia.github.io/
  email:     alessia.visconti@kcl.ac.uk
  twitter:   _alesssia
  mastodon:  mas.to/@alesssia
  github:    alesssia
  orcid:     '0000-0003-4144-2019'

pagination:
  indexpage: 'blog'