# Dependencies
markdown:    kramdown
highlighter: rouge

# Permalinks
permalink:   pretty

# Setup
title:       Alessia Visconti
tagline:     ''
description: 'Computational Biologist, PhD'
url:         http://alesssia.github.io/
baseurl:     /
lastmod:    '20190813'

author:
  name:      'Alessia Visconti'
  url:       http://alesssia.github.io/
  email:     alessia.visconti@kcl.ac.uk
  twitter:   _alesssia
  github:    alesssia
  orcid:     '0000-0003-4144-2019'

pagination:
  indexpage: 'blog'